name: APRN Pi Builder

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:

jobs:
  KiCad_Hardware:
    runs-on: ubuntu-latest
    name: KiCad Hardware

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: INTI-CMNB/KiBot@v2_k6
        with:
          # Config file
          config: Hardware/config.kibot.yaml
          # Prefix for output in config file.
          dir: _hardwareOutput

          # Hardware Files
          schema: "Hardware/APRN-pi_board/APRN-pi.kicad_sch"
          board: "Hardware/APRN-pi_board/APRN-pi.kicad_pcb"

          # Debug
          verbose: 1

      - name: upload results
        uses: actions/upload-artifact@v2
        with:
          name: APRN-Pi-Hardware
          path: _hardwareOutput

  make_docs:
    runs-on: ubuntu-latest
    name: Build Docs
    needs: [KiCad_Hardware]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: sudo apt update

      - run: sudo apt install texlive-latex-recommended texlive-latex-extra texlive-pictures pandoc rename latexmk inkscape imagemagick

      - name: Install requirements
        run: pip install -r Docs/requirements.txt

      # Download artifacts from other builds
      - uses: actions/download-artifact@v2
        with:
          name: APRN-Pi-Hardware
          path: _hardwareOutput

      - run: cd Docs && make latexpdf

      - run: mv Docs/_build/latex/*.pdf Docs/_build/latex/APRN-Pi-Manual.pdf

      - uses: actions/upload-artifact@v2
        with:
          name: APRN-Pi-Manual
          path: Docs/_build/latex/APRN-Pi-Manual.pdf

  publish:
    # Only run on tags
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    name: Publish
    needs: [make_docs, KiCad_Hardware]

    steps:
      # Download artifacts
      - uses: actions/download-artifact@v2
        with:
          name: APRN-Pi-Manual

      - uses: actions/download-artifact@v2
        with:
          name: APRN-Pi-Hardware

      - run: mkdir -p _staging/

      - run: cp *.pdf _staging/

      - run: cp *.step _staging/

      - name: Upload Docs to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "_staging/*"
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: true
          body: "Concord Robotics, Automated with github ci/cd."
          file_glob: true
